# Generated by Django 2.2.9 on 2020-01-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200131_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='galerie',
            name='legend',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
